/* PastorAbayomiBibleStories — Bible Heroes Adventure
   Version 2.0 — 10 playable Bible-story levels, client-side */
(function () {
  'use strict';

  const STORAGE_KEY = 'pabs_bible_heroes_v2';
  const defaultState = { unlockedLevel: 1, scores: {}, stars: {}, badges: {}, totalScore: 0, soundOn: true };
  let state = loadState();
  let currentLevel = null, currentChallenge = 0, levelScore = 0, levelStars = 0, mistakes = 0;

  const LEVELS = {
    1:{title:'David & Goliath',icon:'🏹',badge:{id:'david',name:'DAVID THE BRAVE',icon:'🏹'},intro:'David was a young shepherd who trusted God when Goliath challenged God’s people.',items:[['sling','🪢','Sling',1],['stones','🪨','Smooth Stones',1],['armor','🛡️','Heavy Armor',0],['sword','⚔️','Heavy Sword',0]],quiz:['Who did David face?',['Pharaoh','Goliath','Jonah','Daniel'],1],choice:['What gave David courage?',['His size','His armor','His trust in God','A giant army'],2],lesson:'True courage comes from trusting God. David faced Goliath with faith. 📖 1 Samuel 17'},
    2:{title:'The Walls of Jericho',icon:'🏰',badge:{id:'jericho',name:'FAITHFUL WARRIOR',icon:'🏰'},intro:'Joshua and the Israelites followed God’s instructions as they came to the fortified city of Jericho.',items:[['trumpets','📯','Trumpets',1],['march','👣','Marching',1],['tank','🚙','Tank',0],['cannon','💣','Cannon',0]],quiz:['What happened to Jericho’s walls?',['They fell','They floated away','They became gold','They grew taller'],0],choice:['What did the Israelites do around Jericho?',['They followed God’s instructions','They built a rocket','They sailed away','They hid for seven days'],0],lesson:'Joshua and the Israelites obeyed God’s instructions. 📖 Joshua 6'},
    3:{title:'Joseph and His Dreams',icon:'🌈',badge:{id:'joseph',name:'DREAM KEEPER',icon:'🌈'},intro:'Joseph had dreams about his future and learned that God could work through difficult seasons.',items:[['coat','🧥','Special Coat',1],['dream','💭','Dreams',1],['crown','👑','Pharaoh’s Crown',0],['spaceship','🚀','Spaceship',0]],quiz:['What did Joseph receive that became special to him?',['A special coat','A ship','A trumpet','A lion'],0],choice:['What should we remember from Joseph’s story?',['God can have a purpose for our lives','Never forgive anyone','Give up when life is hard','Ignore wise advice'],0],lesson:'Joseph’s story teaches patience, forgiveness, and trust in God’s purpose. 📖 Genesis 37–50'},
    4:{title:'The Three Hebrew Boys',icon:'🔥',badge:{id:'hebrew',name:'FAITH UNDER FIRE',icon:'🔥'},intro:'Shadrach, Meshach, and Abednego chose to remain faithful to God even when they faced a fiery furnace.',items:[['faith','❤️','Faith in God',1],['courage','🛡️','Courage',1],['idol','🗿','Golden Idol',0],['fear','😨','Giving in to Fear',0]],quiz:['Where were the three Hebrew boys thrown?',['A cave','A fiery furnace','A boat','A palace garden'],1],choice:['What did they choose to do?',['Worship God faithfully','Give up their faith','Run away from everyone','Build a new kingdom'],0],lesson:'They stood firm in faith and trusted God. 📖 Daniel 3'},
    5:{title:'Daniel in the Lions’ Den',icon:'🦁',badge:{id:'daniel',name:'LION’S DEN HERO',icon:'🦁'},intro:'Daniel continued to pray to God even when a new law made prayer dangerous.',items:[['prayer','🙏','Prayer',1],['window','🪟','Open Window',1],['spear','🔱','Spear',0],['crown','👑','King’s Crown',0]],quiz:['Where was Daniel placed?',['A lion’s den','A boat','A vineyard','A workshop'],0],choice:['What did Daniel keep doing?',['Praying to God','Ignoring God','Hiding his Bible','Building a wall'],0],lesson:'Daniel remained faithful in prayer. 📖 Daniel 6'},
    6:{title:'Jonah and the Great Fish',icon:'🐋',badge:{id:'jonah',name:'OBEDIENT MESSENGER',icon:'🐋'},intro:'Jonah learned that running away from God’s instruction was not the answer. He eventually obeyed God’s call.',items:[['fish','🐋','Great Fish',1],['prayer','🙏','Prayer',1],['castle','🏰','Castle',0],['train','🚆','Train',0]],quiz:['Where did Jonah try to go instead of obeying God?',['Nineveh','Tarshish','Jerusalem','Bethlehem'],1],choice:['What lesson does Jonah’s story teach?',['Obey God and respond to His call','Never listen','Always run away','Avoid prayer'],0],lesson:'Jonah learned obedience and repentance. 📖 Jonah 1–4'},
    7:{title:'Noah and the Ark',icon:'🌧️',badge:{id:'noah',name:'ARK BUILDER',icon:'🛶'},intro:'Noah obeyed God and built an ark before the flood, protecting his family and the animals God brought to him.',items:[['ark','🛶','Ark',1],['animals','🐘','Animals',1],['submarine','🚢','Submarine',0],['rocket','🚀','Rocket',0]],quiz:['What did Noah build?',['An ark','A palace','A tower','A temple'],0],choice:['What was Noah known for in this story?',['Obedience to God','Refusing instructions','Building a city','Leading an army'],0],lesson:'Noah’s story highlights faith and obedience. 📖 Genesis 6–9'},
    8:{title:'Moses and the Red Sea',icon:'🌊',badge:{id:'moses',name:'SEA CROSSER',icon:'🌊'},intro:'Moses led the Israelites out of Egypt. God made a way for them through the Red Sea.',items:[['staff','🪵','Moses’ Staff',1],['sandals','👡','Sandals',1],['computer','💻','Computer',0],['anchor','⚓','Anchor',0]],quiz:['What sea did the Israelites cross?',['Dead Sea','Red Sea','Black Sea','Mediterranean Sea'],1],choice:['What did Moses do when the people were afraid?',['Trusted God’s direction','Abandoned them','Built a spaceship','Returned to Pharaoh'],0],lesson:'God made a way where there seemed to be no way. 📖 Exodus 14'},
    9:{title:'Esther’s Courage',icon:'👑',badge:{id:'esther',name:'COURAGEOUS QUEEN',icon:'👑'},intro:'Esther courageously used her position as queen to help protect her people.',items:[['crown','👑','Queen’s Crown',1],['courage','💪','Courage',1],['pirate','🏴‍☠️','Pirate Ship',0],['football','⚽','Football',0]],quiz:['What position did Esther have?',['Queen','Shepherd','Soldier','Fisherman'],0],choice:['Why did Esther show courage?',['To help protect her people','To win a race','To build a tower','To find treasure'],0],lesson:'Esther shows courage, wisdom, and willingness to help others. 📖 Esther 4–7'},
    10:{title:'The Birth of Jesus',icon:'⭐',badge:{id:'jesus',name:'GOOD NEWS HERO',icon:'⭐'},intro:'Jesus was born in Bethlehem. His birth brought a message of hope and good news.',items:[['manger','🪵','Manger',1],['star','⭐','Star',1],['crown','👑','Golden Throne',0],['spaceship','🚀','Spaceship',0]],quiz:['Where was Jesus born?',['Bethlehem','Jericho','Nineveh','Egypt'],0],choice:['What did Jesus’ birth bring?',['Good news and hope','A military battle','A treasure hunt','A new city wall'],0],lesson:'The birth of Jesus is celebrated as good news and great joy. 📖 Luke 2:1–20'},
  };

  const BADGES = Object.keys(LEVELS).map(k => ({id:LEVELS[k].badge.id,name:LEVELS[k].badge.name,icon:LEVELS[k].badge.icon,level:Number(k)}));
  const $ = s => document.querySelector(s), $$ = s => document.querySelectorAll(s);

  function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)return {...defaultState,...JSON.parse(raw)};}catch(e){}return {...defaultState};}
  function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(e){}}
  function showScreen(name){$$('.screen').forEach(s=>s.classList.remove('active'));const el=$(`#screen-${name}`);if(el)el.classList.add('active');if(name==='levels')updateLevelSelect();if(name==='achievements')renderAchievements();}

  function init(){bindEvents();updateSoundButton();updateLevelSelect();showScreen('home');}
  function bindEvents(){
    const on=(id,fn)=>{const el=$(id);if(el)el.addEventListener('click',fn)};
    on('#btn-play',()=>{playSound('click');showScreen('levels')});
    on('#btn-howto',()=>{playSound('click');showScreen('howto')}); on('#btn-stories',()=>{playSound('click');showScreen('stories')}); on('#btn-achievements',()=>{playSound('click');showScreen('achievements')}); on('#btn-parent',()=>{playSound('click');showScreen('parent')}); on('#btn-sound',toggleSound);
    document.body.addEventListener('click',e=>{const g=e.target.closest('[data-goto]');if(g){playSound('click');showScreen(g.dataset.goto)}});
    $$('.level-card').forEach(card=>card.addEventListener('click',()=>{const n=+card.dataset.level;if(n<=state.unlockedLevel){playSound('click');startLevel(n)}else showToast('Complete the previous level to unlock this adventure!')}));
    on('#btn-quit-level',()=>{playSound('click');if(confirm('Leave this level? Progress in this level will be lost.'))showScreen('levels')});
    on('#btn-next-level',()=>{playSound('click');if(currentLevel<10 && state.unlockedLevel>=currentLevel+1)startLevel(currentLevel+1);else showScreen('levels')});
    on('#btn-replay',()=>{playSound('click');startLevel(currentLevel)}); on('#btn-results-home',()=>{playSound('click');showScreen('home')});
  }

  let audioCtx=null;
  function getAudioCtx(){if(!audioCtx){try{audioCtx=new(window.AudioContext||window.webkitAudioContext)()}catch(e){}}return audioCtx;}
  function playTone(f,d,t='sine',v=.12){if(!state.soundOn)return;const c=getAudioCtx();if(!c)return;try{const o=c.createOscillator(),g=c.createGain();o.type=t;o.frequency.value=f;g.gain.value=v;g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d)}catch(e){}}
  function playSound(n){if(!state.soundOn)return;const seq={click:[[600,.08,'square']],correct:[[523,.12],[659,.15],[784,.2]],wrong:[[200,.25,'sawtooth']],complete:[[523,.15],[659,.15],[784,.15],[1046,.3]]}[n]||[];seq.forEach((x,i)=>setTimeout(()=>playTone(x[0],x[1],x[2]||'sine',n==='wrong'?.1:.15),i*110));}
  function toggleSound(){state.soundOn=!state.soundOn;saveState();updateSoundButton();if(state.soundOn)playSound('click');}
  function updateSoundButton(){const b=$('#btn-sound');if(b)b.textContent=state.soundOn?'🔊':'🔇';}

  function updateLevelSelect(){$$('.level-card').forEach(card=>{const n=+card.dataset.level,u=n<=state.unlockedLevel;card.classList.toggle('unlocked',u);card.classList.toggle('locked',!u);const st=card.querySelector('.level-status');if(st)st.textContent=u?(state.stars[n]?'✓ PLAY':'PLAY'):'🔒';const se=$(`#stars-${n}`);if(se){const s=state.stars[n]||0;se.textContent='★'.repeat(s)+'☆'.repeat(3-s)}});const t=$('#total-score');if(t)t.textContent=`⭐ ${state.totalScore}`;}
  function startLevel(n){if(!LEVELS[n])return;currentLevel=n;currentChallenge=0;levelScore=0;levelStars=0;mistakes=0;showScreen('game');updateGameHeader();renderChallenge();}
  function updateGameHeader(){const total=5,pct=(currentChallenge/total)*100;const p=$('#progress-fill');if(p)p.style.width=pct+'%';const i=$('#challenge-indicator');if(i)i.textContent=`Challenge ${Math.min(currentChallenge+1,total)}/${total}`;if($('#game-score'))$('#game-score').textContent=levelScore;if($('#game-stars'))$('#game-stars').textContent='⭐'+levelStars;}
  function renderChallenge(){const c=$('#game-content');if(!c)return;c.innerHTML='';const l=LEVELS[currentLevel];switch(currentChallenge){case 0:renderIntro(l);break;case 1:renderItems(l);break;case 2:renderQuiz(l);break;case 3:renderChoice(l);break;case 4:renderLesson(l);break;default:finishLevel();}updateGameHeader();}
  function renderIntro(l){$('#game-content').innerHTML=`<div class="narrative"><span class="story-emoji">${l.icon}</span><h3>${l.title}</h3><p>${l.intro}</p><p>Complete the challenges, earn stars, and discover the Bible lesson!</p><button class="btn btn-continue" id="continue-intro">LET'S GO! ▶</button></div>`;$('#continue-intro').onclick=()=>{playSound('click');currentChallenge=1;renderChallenge()};}
  function renderItems(l){const c=$('#game-content');c.innerHTML=`<div class="challenge-box"><h3>🎒 Choose the Story Items</h3><p class="instruction">Tap the items that belong in this Bible story.</p><div class="items-grid" id="items-grid"></div><div id="item-feedback"></div><button class="btn btn-continue" id="check-items" disabled>CHECK SELECTION</button></div>`;const grid=$('#items-grid'),selected=[];l.items.forEach(it=>{const d=document.createElement('div');d.className='item-card';d.innerHTML=`<span class="item-emoji">${it[1]}</span>${it[2]}`;d.dataset.correct=it[3];d.onclick=()=>{playSound('click');d.classList.toggle('selected');const idx=selected.indexOf(d);if(idx>=0)selected.splice(idx,1);else selected.push(d);$('#check-items').disabled=!selected.length};grid.appendChild(d)});$('#check-items').onclick=()=>{const good=selected.length===l.items.filter(x=>x[3]).length&&selected.every(x=>x.dataset.correct==='1');if(good){playSound('correct');levelScore+=150;levelStars=Math.max(levelStars,1);$('#item-feedback').innerHTML='<div class="feedback good">✅ Excellent! You chose the right story items.</div>';$('#check-items').textContent='CONTINUE ▶';$('#check-items').onclick=()=>{currentChallenge=2;renderChallenge()};$$('.item-card').forEach(x=>x.style.pointerEvents='none')}else{playSound('wrong');mistakes++;levelScore=Math.max(0,levelScore-20);$('#item-feedback').innerHTML='<div class="feedback bad">Try again. Think about what belongs to this Bible story.</div>';selected.slice().forEach(x=>{if(x.dataset.correct==='0'){x.classList.remove('selected');const i=selected.indexOf(x);if(i>=0)selected.splice(i,1)}})}updateGameHeader()};}
  function renderQuiz(l){const q=l.quiz;$('#game-content').innerHTML=`<div class="challenge-box"><h3>📖 Bible Knowledge</h3><p class="instruction">${q[0]}</p><div class="quiz-options" id="quiz-options"></div><div id="quiz-feedback"></div></div>`;q[1].forEach((a,i)=>{const b=document.createElement('button');b.className='quiz-option';b.textContent=String.fromCharCode(65+i)+'. '+a;b.onclick=()=>answerChoice(b,i===q[2],'quiz');$('#quiz-options').appendChild(b)});}
  function renderChoice(l){const q=l.choice;$('#game-content').innerHTML=`<div class="challenge-box"><h3>💡 Faith Challenge</h3><p class="instruction">${q[0]}</p><div class="quiz-options" id="choice-options"></div><div id="choice-feedback"></div></div>`;q[1].forEach((a,i)=>{const b=document.createElement('button');b.className='quiz-option';b.textContent=String.fromCharCode(65+i)+'. '+a;b.onclick=()=>answerChoice(b,i===q[2],'choice') ;$('#choice-options').appendChild(b)});}
  function answerChoice(btn,correct,type){const container=type==='quiz'?$('#quiz-options'):$('#choice-options');container.querySelectorAll('button').forEach(b=>b.style.pointerEvents='none');const feedback=type==='quiz'?$('#quiz-feedback'):$('#choice-feedback');if(correct){btn.classList.add('correct');playSound('correct');levelScore+=200;levelStars=Math.max(levelStars,2);feedback.innerHTML='<div class="feedback good">✅ Correct! Great Bible knowledge.</div>';}else{btn.classList.add('wrong');playSound('wrong');mistakes++;levelScore=Math.max(0,levelScore-30);container.querySelectorAll('button').forEach(b=>{if(b!==btn&&b.dataset.answer==='correct')b.classList.add('correct')});feedback.innerHTML='<div class="feedback bad">Not quite. Keep learning from the story!</div>';}container.querySelectorAll('button').forEach((b,i)=>{if((type==='quiz'?LEVELS[currentLevel].quiz[2]:LEVELS[currentLevel].choice[2])===i)b.dataset.answer='correct'});feedback.innerHTML += `<button class="btn btn-continue" id="next-answer">CONTINUE ▶</button>`;updateGameHeader();$('#next-answer').onclick=()=>{playSound('click');currentChallenge=type==='quiz'?3:4;renderChallenge()};}
  function renderLesson(l){levelStars=3;$('#game-content').innerHTML=`<div class="lesson-box"><div class="lesson-emoji">💡</div><h3>Bible Lesson</h3><p>${l.lesson}</p><p><strong>Great job, Bible Hero!</strong> Keep learning, trusting God, and putting His Word into practice.</p><div class="verse-ref">📖 Bible Story Reference</div><button class="btn btn-continue" id="finish-level">FINISH LEVEL 🎉</button></div>`;$('#finish-level').onclick=()=>{playSound('click');finishLevel()};}
  function finishLevel(){if(mistakes===0)levelScore+=100;else if(mistakes<=1)levelScore+=50;if(levelScore>=500)levelStars=Math.max(levelStars,2);if(mistakes===0&&levelScore>=700)levelStars=3;levelStars=Math.max(1,Math.min(3,levelStars));const prev=state.scores[currentLevel]||0;if(levelScore>prev){state.totalScore=state.totalScore-prev+levelScore;state.scores[currentLevel]=levelScore}state.stars[currentLevel]=Math.max(state.stars[currentLevel]||0,levelStars);if(currentLevel<10)state.unlockedLevel=Math.max(state.unlockedLevel,currentLevel+1);state.badges[LEVELS[currentLevel].badge.id]=true;saveState();playSound('complete');showResults();}
  function showResults(){showScreen('results');const l=LEVELS[currentLevel];$('#results-title').textContent='LEVEL COMPLETE!';$('#results-stars').textContent='⭐'.repeat(levelStars)+'☆'.repeat(3-levelStars);$('#results-score-val').textContent=levelScore;$('#badge-name').textContent=l.badge.name;$('#results-lesson').textContent=`You completed ${l.title} and learned a valuable Bible lesson!`;const b=$('#btn-next-level');if(currentLevel<10){b.style.display='block';b.textContent='PLAY NEXT LEVEL'}else{b.style.display='block';b.textContent='ALL 10 LEVELS COMPLETE! 🎉'}}
  function renderAchievements(){const g=$('#badges-grid');if(!g)return;g.innerHTML='';BADGES.forEach(b=>{const u=!!state.badges[b.id],d=document.createElement('div');d.className='badge-card'+(u?' unlocked':'');d.innerHTML=`<span class="b-icon">${u?b.icon:'🔒'}</span><span class="b-name">${b.name}</span>`;g.appendChild(d)});$('#ach-total-score').textContent=state.totalScore;$('#ach-levels').textContent=Object.keys(state.stars).length;$('#ach-stars').textContent=Object.values(state.stars).reduce((a,b)=>a+b,0);}
  let toastTimer;function showToast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add('hidden'),2500)}
  document.addEventListener('DOMContentLoaded',init);
})();
