/* PastorAbayomiBibleStories — Bible Heroes Adventure
   Version 3.0 — 10 playable Bible-story levels with action mini-games
*/
(function(){
'use strict';
const STORAGE_KEY='pabs_bible_heroes_v3';
const defaultState={unlockedLevel:1,scores:{},stars:{},badges:{},totalScore:0,soundOn:true};
let state=loadState(),currentLevel=null,currentChallenge=0,levelScore=0,levelStars=0,mistakes=0,actionTimer=null;

const LEVELS={
1:{title:'David & Goliath',icon:'🏹',badge:{id:'david',name:'DAVID THE BRAVE',icon:'🏹'},intro:'David was a young shepherd who trusted God when Goliath challenged God’s people.',items:[['sling','🪢','Sling',1],['stones','🪨','Smooth Stones',1],['staff','🪵','Shepherd Staff',1],['armor','🛡️','Heavy Armor',0],['sword','⚔️','Heavy Sword',0]],quiz:['Who did David face?',['Pharaoh','Goliath','Jonah','Daniel'],1],action:{type:'target',title:'🏹 Sling Shot Challenge',instruction:'Move the aim and tap FIRE to hit the target. No graphic combat—just a fun target challenge!',target:'🎯',player:'🧒',success:'Bullseye! David trusted God and showed courage.'},lesson:'True courage comes from trusting God. David faced Goliath with faith. 📖 1 Samuel 17'},
2:{title:'The Walls of Jericho',icon:'🏰',badge:{id:'jericho',name:'FAITHFUL WARRIOR',icon:'🏰'},intro:'Joshua and the Israelites followed God’s instructions as they came to Jericho.',items:[['trumpets','📯','Trumpets',1],['march','👣','Marching Feet',1],['ark','📦','Ark of the Covenant',1],['tank','🚙','Tank',0],['cannon','💣','Cannon',0]],quiz:['What happened to Jericho’s walls?',['They fell','They floated away','They became gold','They grew taller'],0],action:{type:'march',title:'📯 Jericho March',instruction:'Tap the trumpet and marching buttons in the correct rhythm to complete the march around Jericho.',success:'The march is complete! The walls came down after the people followed God’s instructions.'},lesson:'Joshua and the Israelites obeyed God’s instructions. 📖 Joshua 6'},
3:{title:'Joseph and His Dreams',icon:'🌈',badge:{id:'joseph',name:'DREAM KEEPER',icon:'🌈'},intro:'Joseph had dreams about his future and learned that God could work through difficult seasons.',items:[['coat','🧥','Special Coat',1],['dream','💭','Dreams',1],['grain','🌾','Sheaves of Grain',1],['spaceship','🚀','Spaceship',0],['skate','🛹','Skateboard',0]],quiz:['What did Joseph receive that became special to him?',['A special coat','A ship','A trumpet','A lion'],0],action:{type:'collect',title:'🌾 Gather Joseph’s Dreams',instruction:'Catch the falling dream symbols and grain. Collect 8 before time runs out!',success:'Wonderful! You gathered the dream symbols and remembered Joseph’s story.'},lesson:'Joseph’s story teaches patience, forgiveness, and trust in God’s purpose. 📖 Genesis 37–50'},
4:{title:'The Three Hebrew Boys',icon:'🔥',badge:{id:'hebrew',name:'FAITH UNDER FIRE',icon:'🔥'},intro:'Shadrach, Meshach, and Abednego chose to remain faithful to God even when they faced a fiery furnace.',items:[['faith','❤️','Faith in God',1],['courage','🛡️','Courage',1],['prayer','🙏','Prayer',1],['idol','🗿','Golden Idol',0],['fear','😨','Giving in to Fear',0]],quiz:['Where were the three Hebrew boys thrown?',['A cave','A fiery furnace','A boat','A palace garden'],1],action:{type:'dodge',title:'🔥 Faith Through the Fire',instruction:'Move left and right to help the three friends avoid the falling fireballs. Survive for 12 seconds!',success:'You made it through! Their faith stayed strong even in the fire.'},lesson:'They stood firm in faith and trusted God. 📖 Daniel 3'},
5:{title:'Daniel in the Lions’ Den',icon:'🦁',badge:{id:'daniel',name:'LION’S DEN HERO',icon:'🦁'},intro:'Daniel continued to pray to God even when a new law made prayer dangerous.',items:[['prayer','🙏','Prayer',1],['window','🪟','Open Window',1],['lion','🦁','Lion',1],['spear','🔱','Spear',0],['crown','👑','King’s Crown',0]],quiz:['Where was Daniel placed?',['A lion’s den','A boat','A vineyard','A workshop'],0],action:{type:'light',title:'🦁 Daniel’s Faith Light',instruction:'Tap the prayer symbols before the timer ends. Keep the den peaceful and bright!',success:'The den stayed peaceful! Daniel remained faithful in prayer.'},lesson:'Daniel remained faithful in prayer. 📖 Daniel 6'},
6:{title:'Jonah and the Great Fish',icon:'🐋',badge:{id:'jonah',name:'OBEDIENT MESSENGER',icon:'🐋'},intro:'Jonah learned that running away from God’s instruction was not the answer. He eventually obeyed God’s call.',items:[['fish','🐋','Great Fish',1],['prayer','🙏','Prayer',1],['boat','⛵','Ship',1],['castle','🏰','Castle',0],['train','🚆','Train',0]],quiz:['Where did Jonah try to go instead of obeying God?',['Nineveh','Tarshish','Jerusalem','Bethlehem'],1],action:{type:'swim',title:'🌊 Jonah’s Sea Journey',instruction:'Guide Jonah’s boat through the waves and collect 6 prayer stars. Avoid the rocks!',success:'Safe journey! Jonah learned to listen and obey God.'},lesson:'Jonah learned obedience and repentance. 📖 Jonah 1–4'},
7:{title:'Noah and the Ark',icon:'🛶',badge:{id:'noah',name:'ARK BUILDER',icon:'🛶'},intro:'Noah obeyed God and built an ark before the flood, protecting his family and the animals God brought to him.',items:[['ark','🛶','Ark',1],['animals','🐘','Animals',1],['wood','🪵','Wood',1],['submarine','🚢','Submarine',0],['rocket','🚀','Rocket',0]],quiz:['What did Noah build?',['An ark','A palace','A tower','A temple'],0],action:{type:'collect',title:'🛶 Load the Ark',instruction:'Tap the animals as they appear. Bring 8 animals safely aboard before time runs out!',success:'All aboard! You helped Noah prepare the ark.'},lesson:'Noah’s story highlights faith and obedience. 📖 Genesis 6–9'},
8:{title:'Moses and the Red Sea',icon:'🌊',badge:{id:'moses',name:'SEA CROSSER',icon:'🌊'},intro:'Moses led the Israelites out of Egypt. God made a way for them through the Red Sea.',items:[['staff','🪵','Moses’ Staff',1],['sandals','👡','Sandals',1],['people','👨‍👩‍👧','Israelites',1],['computer','💻','Computer',0],['anchor','⚓','Anchor',0]],quiz:['What sea did the Israelites cross?',['Dead Sea','Red Sea','Black Sea','Mediterranean Sea'],1],action:{type:'path',title:'🌊 Cross the Red Sea',instruction:'Tap the safe stepping stones from left to right. Find the path across the sea!',success:'You crossed safely! God made a way for His people.'},lesson:'God made a way where there seemed to be no way. 📖 Exodus 14'},
9:{title:'Esther’s Courage',icon:'👑',badge:{id:'esther',name:'COURAGEOUS QUEEN',icon:'👑'},intro:'Esther courageously used her position as queen to help protect her people.',items:[['crown','👑','Queen’s Crown',1],['courage','💪','Courage',1],['scroll','📜','Royal Scroll',1],['pirate','🏴‍☠️','Pirate Ship',0],['football','⚽','Football',0]],quiz:['What position did Esther have?',['Queen','Shepherd','Soldier','Fisherman'],0],action:{type:'choice',title:'👑 Esther’s Courage Mission',instruction:'Choose the brave actions that help Esther speak up wisely and help her people.',success:'Courageous choice! Esther used wisdom and courage to help others.'},lesson:'Esther shows courage, wisdom, and willingness to help others. 📖 Esther 4–7'},
10:{title:'The Birth of Jesus',icon:'⭐',badge:{id:'jesus',name:'GOOD NEWS HERO',icon:'⭐'},intro:'Jesus was born in Bethlehem. His birth brought a message of hope and good news.',items:[['manger','🪵','Manger',1],['star','⭐','Bethlehem Star',1],['shepherds','🐑','Shepherds',1],['spaceship','🚀','Spaceship',0],['castle','🏰','Modern Castle',0]],quiz:['Where was Jesus born?',['Bethlehem','Jericho','Nineveh','Egypt'],0],action:{type:'stars',title:'⭐ Follow the Bethlehem Star',instruction:'Tap 10 stars to guide the journey to Bethlehem and celebrate the good news!',success:'You followed the star! What joyful good news.'},lesson:'The birth of Jesus is celebrated as good news and great joy. 📖 Luke 2:1–20'}
};
const BADGES=Object.keys(LEVELS).map(k=>({id:LEVELS[k].badge.id,name:LEVELS[k].badge.name,icon:LEVELS[k].badge.icon,level:+k}));
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)return {...defaultState,...JSON.parse(raw)};}catch(e){}return {...defaultState};}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(e){}}
function showScreen(name){$$('.screen').forEach(s=>s.classList.remove('active'));const el=$(`#screen-${name}`);if(el)el.classList.add('active');if(name==='levels')updateLevelSelect();if(name==='achievements')renderAchievements();}
function init(){bindEvents();updateSoundButton();updateLevelSelect();showScreen('home');}
function bindEvents(){const on=(id,fn)=>{const e=$(id);if(e)e.addEventListener('click',fn)};on('#btn-play',()=>{playSound('click');showScreen('levels')});on('#btn-howto',()=>{playSound('click');showScreen('howto')});on('#btn-stories',()=>{playSound('click');showScreen('stories')});on('#btn-achievements',()=>{playSound('click');showScreen('achievements')});on('#btn-parent',()=>{playSound('click');showScreen('parent')});on('#btn-sound',toggleSound);document.body.addEventListener('click',e=>{const g=e.target.closest('[data-goto]');if(g){playSound('click');showScreen(g.dataset.goto)}});$$('.level-card').forEach(card=>card.addEventListener('click',()=>{const n=+card.dataset.level;if(n<=state.unlockedLevel){playSound('click');startLevel(n)}else showToast('Complete the previous level to unlock this adventure!')}));on('#btn-quit-level',()=>{playSound('click');clearActionTimer();if(confirm('Leave this level? Progress in this level will be lost.'))showScreen('levels')});on('#btn-next-level',()=>{playSound('click');if(currentLevel<10&&state.unlockedLevel>=currentLevel+1)startLevel(currentLevel+1);else showScreen('levels')});on('#btn-replay',()=>{playSound('click');startLevel(currentLevel)});on('#btn-results-home',()=>{playSound('click');showScreen('home')});}
let audioCtx=null;function getAudioCtx(){if(!audioCtx){try{audioCtx=new(window.AudioContext||window.webkitAudioContext)()}catch(e){}}return audioCtx;}function playTone(f,d,t='sine',v=.12){if(!state.soundOn)return;const c=getAudioCtx();if(!c)return;try{const o=c.createOscillator(),g=c.createGain();o.type=t;o.frequency.value=f;g.gain.value=v;g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d)}catch(e){}}
function playSound(n){if(!state.soundOn)return;const seq={click:[[600,.08,'square']],correct:[[523,.12],[659,.15],[784,.2]],wrong:[[200,.25,'sawtooth']],action:[[440,.08],[660,.08],[880,.12]],complete:[[523,.15],[659,.15],[784,.15],[1046,.3]]}[n]||[];seq.forEach((x,i)=>setTimeout(()=>playTone(x[0],x[1],x[2]||'sine',n==='wrong'?.1:.15),i*100));}
function toggleSound(){state.soundOn=!state.soundOn;saveState();updateSoundButton();if(state.soundOn)playSound('click');}function updateSoundButton(){const b=$('#btn-sound');if(b)b.textContent=state.soundOn?'🔊':'🔇';}
function updateLevelSelect(){const hs=$('#home-score');if(hs)hs.textContent=state.totalScore;const hb=$('#home-badges');if(hb)hb.textContent=Object.keys(state.badges).length;$$('.level-card').forEach(card=>{const n=+card.dataset.level,u=n<=state.unlockedLevel;card.classList.toggle('unlocked',u);card.classList.toggle('locked',!u);const st=card.querySelector('.level-status');if(st)st.textContent=u?(state.stars[n]?'✓ PLAY':'PLAY'):'🔒';const se=$(`#stars-${n}`);if(se){const s=state.stars[n]||0;se.textContent='★'.repeat(s)+'☆'.repeat(3-s)}});const t=$('#total-score');if(t)t.textContent=`⭐ ${state.totalScore}`;}
function startLevel(n){if(!LEVELS[n])return;clearActionTimer();currentLevel=n;currentChallenge=0;levelScore=0;levelStars=0;mistakes=0;showScreen('game');updateGameHeader();renderChallenge();}
function updateGameHeader(){const total=5,pct=(currentChallenge/total)*100;if($('#progress-fill'))$('#progress-fill').style.width=pct+'%';if($('#challenge-indicator'))$('#challenge-indicator').textContent=`Challenge ${Math.min(currentChallenge+1,total)}/${total}`;if($('#game-score'))$('#game-score').textContent=levelScore;if($('#game-stars'))$('#game-stars').textContent='⭐'+levelStars;}
function nextChallenge(){playSound('click');currentChallenge++;renderChallenge();}
function renderChallenge(){clearActionTimer();const c=$('#game-content');if(!c)return;c.innerHTML='';const l=LEVELS[currentLevel];switch(currentChallenge){case 0:renderIntro(l);break;case 1:renderItems(l);break;case 2:renderQuiz(l);break;case 3:renderAction(l);break;case 4:renderLesson(l);break;default:finishLevel();}updateGameHeader();}
function renderIntro(l){$('#game-content').innerHTML=`<div class="narrative"><span class="story-emoji">${l.icon}</span><h3>${l.title}</h3><p>${l.intro}</p><p>Complete the challenges, play the action mission, earn stars, and discover the Bible lesson!</p><button class="btn btn-continue" id="continue-intro">LET'S GO! ▶</button></div>`;$('#continue-intro').onclick=nextChallenge;}
function renderItems(l){const c=$('#game-content');c.innerHTML=`<div class="challenge-box"><h3>🎒 Choose the Story Items</h3><p class="instruction">Tap the items that belong in this Bible story.</p><div class="items-grid" id="items-grid"></div><div id="item-feedback"></div><button class="btn btn-continue" id="check-items" disabled>CHECK SELECTION</button></div>`;const grid=$('#items-grid'),selected=[];l.items.forEach(it=>{const d=document.createElement('div');d.className='item-card';d.innerHTML=`<span class="item-emoji">${it[1]}</span>${it[2]}`;d.dataset.correct=it[3];d.onclick=()=>{playSound('click');d.classList.toggle('selected');const idx=selected.indexOf(d);if(idx>=0)selected.splice(idx,1);else selected.push(d);$('#check-items').disabled=!selected.length};grid.appendChild(d)});$('#check-items').onclick=()=>{const good=selected.length===l.items.filter(x=>x[3]).length&&selected.every(x=>x.dataset.correct==='1');if(good){playSound('correct');levelScore+=150;levelStars=Math.max(levelStars,1);$('#item-feedback').innerHTML='<div class="feedback good">✅ Excellent! You chose the right story items.</div>';const b=$('#check-items');b.textContent='CONTINUE ▶';b.onclick=nextChallenge;$$('.item-card').forEach(x=>x.style.pointerEvents='none');}else{playSound('wrong');mistakes++;levelScore=Math.max(0,levelScore-20);$('#item-feedback').innerHTML='<div class="feedback bad">Try again. Think about what belongs in this Bible story.</div>';selected.filter(x=>x.dataset.correct==='0').forEach(x=>x.classList.remove('selected'));}updateGameHeader();};}
function renderQuiz(l){const q=l.quiz;$('#game-content').innerHTML=`<div class="challenge-box"><h3>📖 Bible Knowledge</h3><p class="instruction">${q[0]}</p><div class="quiz-options" id="quiz-options"></div><div id="quiz-feedback"></div></div>`;q[1].forEach((a,i)=>{const b=document.createElement('button');b.className='quiz-option';b.textContent=String.fromCharCode(65+i)+'. '+a;b.dataset.correct=i===q[2]?'1':'0';b.onclick=()=>answerChoice(b,i===q[2]);$('#quiz-options').appendChild(b)});}
function answerChoice(btn,correct){const container=$('#quiz-options');container.querySelectorAll('button').forEach(b=>b.style.pointerEvents='none');if(correct){btn.classList.add('correct');playSound('correct');levelScore+=200;levelStars=Math.max(levelStars,2);$('#quiz-feedback').innerHTML='<div class="feedback good">✅ Correct! Great Bible knowledge.</div>';}else{btn.classList.add('wrong');playSound('wrong');mistakes++;levelScore=Math.max(0,levelScore-30);container.querySelectorAll('button').forEach(b=>{if(b.dataset.correct==='1')b.classList.add('correct')});$('#quiz-feedback').innerHTML='<div class="feedback bad">Not quite. Keep learning from the story!</div>';}$('#quiz-feedback').innerHTML+=`<button class="btn btn-continue" id="next-answer">CONTINUE ▶</button>`;updateGameHeader();$('#next-answer').onclick=nextChallenge;}
function renderAction(l){const a=l.action;const c=$('#game-content');c.innerHTML=`<div class="action-box"><div class="action-badge">ACTION MISSION</div><h3>${a.title}</h3><p class="instruction">${a.instruction}</p><div class="action-arena" id="action-arena"></div><div class="action-stats"><span id="action-progress">0 / 0</span><span id="action-time"></span></div><div id="action-feedback"></div></div>`;const arena=$('#action-arena');playSound('action');({target:actionTarget,march:actionMarch,collect:actionCollect,dodge:actionDodge,light:actionLight,swim:actionSwim,path:actionPath,choice:actionChoice,stars:actionStars}[a.type]||actionTarget)(a,arena);}
function actionDone(points=300){clearActionTimer();levelScore+=points;levelStars=Math.max(levelStars,3);playSound('correct');const f=$('#action-feedback');if(f)f.innerHTML=`<div class="feedback good">🎉 ${LEVELS[currentLevel].action.success}</div><button class="btn btn-continue" id="action-next">CONTINUE ▶</button>`;if($('#action-next'))$('#action-next').onclick=nextChallenge;updateGameHeader();}
function clearActionTimer(){if(actionTimer){clearInterval(actionTimer);clearTimeout(actionTimer);actionTimer=null;}}
function actionTarget(a,arena){arena.innerHTML=`<div class="target-scene"><div class="target-player">${a.player}</div><div class="target-ring" id="target-ring">${a.target}</div><div class="crosshair" id="crosshair">✦</div></div><div class="action-controls"><button class="aim-btn" id="aim-left">◀</button><button class="aim-btn fire-btn" id="action-fire">FIRE! 🎯</button><button class="aim-btn" id="aim-right">▶</button></div>`;let pos=0;const x=$('#crosshair');const move=d=>{pos=Math.max(-3,Math.min(3,pos+d));x.style.transform=`translateX(${pos*34}px)`;playSound('click')};$('#aim-left').onclick=()=>move(-1);$('#aim-right').onclick=()=>move(1);$('#action-fire').onclick=()=>{if(pos===0){x.classList.add('hit');actionDone(350)}else{mistakes++;levelScore=Math.max(0,levelScore-25);playSound('wrong');$('#action-feedback').innerHTML='<div class="feedback bad">Almost! Center the target and fire again.</div>';x.classList.add('miss');setTimeout(()=>x.classList.remove('miss'),350);updateGameHeader();}};}
function actionMarch(a,arena){arena.innerHTML=`<div class="jericho-scene"><div class="jericho-wall">🏰 🧱 🧱 🧱 🧱</div><div class="march-count" id="march-count">0 / 7</div><div class="action-controls"><button class="aim-btn" id="trumpet">📯 TRUMPET</button><button class="aim-btn" id="march">👣 MARCH</button></div><p class="mini-hint">Tap TRUMPET, then MARCH. Repeat 7 times.</p></div>`;let n=0,last='';const check=(type)=>{if(type==='trumpet'){last='t';playSound('action')}else if(type==='march'&&last==='t'){n++;last='';playSound('action');$('#march-count').textContent=`${n} / 7`;if(n>=7)actionDone(340)}else{mistakes++;playSound('wrong');showToast('Trumpet first, then march!');}};$('#trumpet').onclick=()=>check('trumpet');$('#march').onclick=()=>check('march');}
function actionCollect(a,arena){arena.innerHTML=`<div class="collect-scene" id="collect-scene"><div class="collect-player">🧒</div></div>`;let n=0;const goal=8;const update=()=>{$('#action-progress').textContent=`${n} / ${goal}`};const spawn=()=>{if(n>=goal)return;const el=document.createElement('button');el.className='collect-item';el.textContent=currentLevel===7?'🐘':(Math.random()>.5?'💭':'🌾');el.style.left=(8+Math.random()*78)+'%';el.style.top=(8+Math.random()*72)+'%';el.onclick=()=>{n++;el.remove();playSound('action');update();if(n>=goal)actionDone(350);else spawn()};arena.querySelector('.collect-scene').appendChild(el)};update();for(let i=0;i<4;i++)spawn();}
function actionDodge(a,arena){arena.innerHTML=`<div class="dodge-scene" id="dodge-scene"><div class="dodge-player" id="dodge-player">👨‍👦</div><div class="fire-stream"></div></div><div class="action-controls"><button class="aim-btn" id="dodge-left">◀ MOVE</button><button class="aim-btn" id="dodge-right">MOVE ▶</button></div>`;let p=50,time=12;const player=$('#dodge-player');const move=d=>{p=Math.max(12,Math.min(88,p+d));player.style.left=p+'%';playSound('click')};$('#dodge-left').onclick=()=>move(-10);$('#dodge-right').onclick=()=>move(10);actionTimer=setInterval(()=>{time--;$('#action-time').textContent=`${time}s`;if(time<=0)actionDone(360);},1000);$('#action-time').textContent='12s';}
function actionLight(a,arena){arena.innerHTML=`<div class="light-scene" id="light-scene"><div class="lion-den">🦁 &nbsp; 🦁 &nbsp; 🦁</div></div>`;let n=0,goal=7;const update=()=>$('#action-progress').textContent=`${n} / ${goal}`;const spawn=()=>{if(n>=goal)return;const b=document.createElement('button');b.className='prayer-light';b.textContent='🙏';b.style.left=(8+Math.random()*82)+'%';b.style.top=(10+Math.random()*70)+'%';b.onclick=()=>{n++;b.remove();playSound('action');update();if(n>=goal)actionDone(340);else spawn()};$('#light-scene').appendChild(b)};update();for(let i=0;i<4;i++)spawn();}
function actionSwim(a,arena){arena.innerHTML=`<div class="swim-scene" id="swim-scene"><div class="boat" id="boat">⛵</div><div class="wave">🌊🌊🌊🌊🌊</div></div><div class="action-controls"><button class="aim-btn" id="swim-left">◀</button><button class="aim-btn" id="swim-right">▶</button></div>`;let p=45,n=0;const boat=$('#boat');const move=d=>{p=Math.max(8,Math.min(82,p+d));boat.style.left=p+'%';playSound('click');n++;if(n>=10)actionDone(330)};$('#swim-left').onclick=()=>move(-7);$('#swim-right').onclick=()=>move(7);}
function actionPath(a,arena){const safe=Math.floor(Math.random()*4);arena.innerHTML=`<div class="path-scene"><div class="sea">🌊 🌊 🌊 🌊</div><div class="stones" id="stones"></div></div>`;const s=$('#stones');for(let i=0;i<4;i++){const b=document.createElement('button');b.className='stone-step';b.textContent='🪨';b.onclick=()=>{if(i===safe){playSound('action');actionDone(350)}else{mistakes++;playSound('wrong');showToast('Try another stepping stone!');updateGameHeader();}};s.appendChild(b);}}
function actionChoice(a,arena){const opts=['Speak wisely and ask for help','Stay silent even when others need help','Give up immediately'];arena.innerHTML=`<div class="palace-scene"><div class="queen">👑 Esther</div><div class="quiz-options" id="action-choice-options"></div></div>`;opts.forEach((o,i)=>{const b=document.createElement('button');b.className='quiz-option';b.textContent=String.fromCharCode(65+i)+'. '+o;b.onclick=()=>{if(i===0)actionDone(350);else{mistakes++;b.classList.add('wrong');playSound('wrong');showToast('Think about Esther’s courage and wisdom.');updateGameHeader();}};$('#action-choice-options').appendChild(b)});}
function actionStars(a,arena){arena.innerHTML=`<div class="star-scene" id="star-scene"><div class="star-guide">🐑 👶 ⭐</div></div>`;let n=0,goal=10;const update=()=>$('#action-progress').textContent=`${n} / ${goal}`;const spawn=()=>{if(n>=goal)return;const b=document.createElement('button');b.className='fall-star';b.textContent='⭐';b.style.left=(5+Math.random()*88)+'%';b.style.top=(8+Math.random()*75)+'%';b.onclick=()=>{n++;b.remove();playSound('action');update();if(n>=goal)actionDone(360);else spawn()};$('#star-scene').appendChild(b)};update();for(let i=0;i<5;i++)spawn();}
function renderLesson(l){levelStars=Math.max(levelStars,2);$('#game-content').innerHTML=`<div class="lesson-box"><div class="lesson-emoji">💡</div><h3>Bible Lesson</h3><p>${l.lesson}</p><p><strong>Great job, Bible Hero!</strong> Keep learning, trusting God, and putting His Word into practice.</p><div class="verse-ref">📖 Bible Story Reference</div><button class="btn btn-continue" id="finish-level">FINISH LEVEL 🎉</button></div>`;$('#finish-level').onclick=()=>{playSound('click');finishLevel()};}
function finishLevel(){clearActionTimer();if(mistakes===0)levelScore+=100;else if(mistakes<=1)levelScore+=50;if(levelScore>=500)levelStars=Math.max(levelStars,2);if(mistakes===0&&levelScore>=800)levelStars=3;levelStars=Math.max(1,Math.min(3,levelStars));const prev=state.scores[currentLevel]||0;if(levelScore>prev){state.totalScore=state.totalScore-prev+levelScore;state.scores[currentLevel]=levelScore}state.stars[currentLevel]=Math.max(state.stars[currentLevel]||0,levelStars);if(currentLevel<10)state.unlockedLevel=Math.max(state.unlockedLevel,currentLevel+1);state.badges[LEVELS[currentLevel].badge.id]=true;saveState();playSound('complete');showResults();}
function showResults(){showScreen('results');const l=LEVELS[currentLevel];$('#results-title').textContent='LEVEL COMPLETE!';$('#results-stars').textContent='⭐'.repeat(levelStars)+'☆'.repeat(3-levelStars);$('#results-score-val').textContent=levelScore;$('#badge-name').textContent=l.badge.name;$('#results-lesson').textContent=`You completed ${l.title} and learned a valuable Bible lesson!`;const b=$('#btn-next-level');if(currentLevel<10){b.style.display='block';b.textContent='PLAY NEXT LEVEL'}else{b.style.display='block';b.textContent='ALL 10 LEVELS COMPLETE! 🎉'}}
function renderAchievements(){const g=$('#badges-grid');if(!g)return;g.innerHTML='';BADGES.forEach(b=>{const u=!!state.badges[b.id],d=document.createElement('div');d.className='badge-card'+(u?' unlocked':'');d.innerHTML=`<span class="b-icon">${u?b.icon:'🔒'}</span><span class="b-name">${b.name}</span>`;g.appendChild(d)});$('#ach-total-score').textContent=state.totalScore;$('#ach-levels').textContent=Object.keys(state.stars).length;$('#ach-stars').textContent=Object.values(state.stars).reduce((a,b)=>a+b,0);}
let toastTimer;function showToast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add('hidden'),1800);}
document.addEventListener('DOMContentLoaded',init);
})();
